#!/bin/bash
#
######################
#
# install-puppet
#
# Script to bootstrap configuration management
#
# This script installs and configures puppet on centos 7
#
# don't run as root or sudo
#
######################
#
# variables are stored in bootstrap.cfg
# review those settings before running this script

source ./bootstrap.cfg 

######################

clear

printf "\n"
printf "########## Set up local puppet storage ################\n"
printf "\n"
printf "Ensure a puppet group is available\n"
printf "\n"
printf "If this script actually creates the group then you will need to\n"
printf "log off and back in after you run this script\n"
printf "\n"

sudo groupadd -g "$PUPPET_GID" puppet
sudo usermod -a -G puppet "$USER"

printf "\n"
printf "Create the local directories\n"
printf " The root is "$PUPPET_ROOT"\n"
printf "\n"

if [ ! -d "$PUPPET_ROOT" ]
then
   #make the directories
   sudo mkdir -p "$PUPPET_ROOT"

   sudo mkdir -p ""$PUPPET_ROOT"/environments"

   sudo mkdir -p ""$PUPPET_ROOT"/environments/production"
   sudo mkdir -p ""$PUPPET_ROOT"/environments/test"
   sudo mkdir -p ""$PUPPET_ROOT"/environments/development"

   sudo mkdir -p ""$PUPPET_ROOT"/environments/production/manifests"
   sudo mkdir -p ""$PUPPET_ROOT"/environments/production/modules"
   sudo mkdir -p ""$PUPPET_ROOT"/environments/development/manifests"
   sudo mkdir -p ""$PUPPET_ROOT"/environments/development/modules"
   sudo mkdir -p ""$PUPPET_ROOT"/environments/test/manifests"
   sudo mkdir -p ""$PUPPET_ROOT"/environments/test/modules"

   sudo chown -R root:puppet "$PUPPET_ROOT" 

   sudo chmod -R 770 "$PUPPET_ROOT" 
   sudo chmod -R g+s "$PUPPET_ROOT"

   sudo ln -s "$PUPPET_ROOT" /etc
fi

printf "\n"
read -p "Press [Enter] key to continue"
clear

######################
#
printf "\n"
printf "################ Configure Time Services  ##############\n"
printf "\n"
printf "Configuration needs good timekeeping...Using chrony\n"

sudo systemctl enable chronyd 
sudo systemctl start chronyd 

printf "\n"
read -p "Press [Enter] key to continue"
clear

######################
#
printf "\n"
printf "################ Ensure nslookups working ###############\n"
printf "\n"
printf "Check the hostname command\n"
printf "\n"

HOSTNAME=`hostname`
if [ "$HOSTNAME" != "$MY_FQDN" ]
then
     
     printf "Fixing hostname\n"
     printf "\n"
     sudo hostnamectl --static set-hostname "$MY_FQDN"
     printf "\n"
fi

if [ -n "$( grep "$HOSTNAME" /etc/hosts )" ]
then
     sudo sed -i "s/$HOSTNAME/$MY_FQDN/g" /etc/hosts

elif [ -n "$( grep "$MY_FQDN" /etc/hosts )"]
then
     HOSTS_LINE="$MY_IP" 
     HOSTS_LINE=""$HOSTS_LINE" "$MY_FQDN"" 
     HOSTS_LINE=""$HOSTS_LINE" "$MY_HOSTNAME""
     printf "$HOSTS_LINE\n"
     printf "\n"
     sudo echo -e $HOSTS_LINE | sudo tee --append /etc/hosts > /dev/null
fi

printf "\n"
read -p "Press [Enter] key to continue"
clear

######################
#
printf "\n"
printf "################## Install Puppet ####################\n"
printf "\n"

sudo rpm -ivh $PUPPET_REPO
sudo yum update -y

sudo yum install puppet -y

printf "\n"
printf " Running a version command you should not see errors\n"
puppet --version
printf "\n"

read -p "Press [Enter] key to continue"
clear

######################
#
printf "\n"
printf "Creating a Puppet Apply command called papply\n"
printf "\n"

if [ ! -e "$LOCAL_FOLDER"/papply ]
then

   #$PUPPET_APPLY="$MANIFEST_DIR/site.pp --modulepath=$MODULE_DIR $*"
   printf "#\!/bin/bash\n"         >  "$LOCAL_FOLDER"/papply
   printf "\n"                     >> "$LOCAL_FOLDER"/papply
   printf "sudo puppet apply "     >> "$LOCAL_FOLDER"/papply
   printf "$MANIFEST_DIR"          >> "$LOCAL_FOLDER"/papply
   printf ' --modulepath='         >> "$LOCAL_FOLDER"/papply
   printf "$MODULE_DIR"            >> "$LOCAL_FOLDER"/papply
   printf ' $*'                    >> "$LOCAL_FOLDER"/papply
   printf "\n"                     >> "$LOCAL_FOLDER"/papply
fi

sudo cp "$LOCAL_FOLDER/papply" "$PUPPET_APPLY_DIR"
sudo chown root:puppet "$PUPPET_APPLY_DIR/papply"
sudo chmod 770 "$PUPPET_APPLY_DIR/papply"

read -p "Press [Enter] key to continue"
clear

#######  EOF  #################################################
