#!/bin/bash
#############
#
# install-hiera
#
# Configure install hiera for puppet
#
#############
#
# Get any variables
#
# Inspect bootstrap.cfg before you execute this script
#
source ./bootstrap.cfg

#############
#
# make sure puppet can see hiera

if ! grep -q 'hiera_config' "$PUPPET_ROOT"/puppet.conf
then
   printf "No heira_config -- Making it\n"
   printf "\n"
   printf "hiera_config = /etc/hiera.yaml\n"
   printf "\n"
   sudo sed -i 's/\[main\]/&\n /' "$PUPPET_ROOT"/puppet.conf
   sudo sed -i 's/\[main\]/&\n    hiera_config = \/etc\/hiera.yaml/' "$PUPPET_ROOT"/puppet.conf
   sudo sed -i 's/\[main\]/&\n    \# Hiera Path/' "$PUPPET_ROOT"/puppet.conf
   sudo sed -i 's/\[main\]/&\n /' "$PUPPET_ROOT"/puppet.conf
fi

printf "\n"
read -p "### Press [Enter] key to continue ###"
clear

#############
#

# manage hiera here
printf "\n" 
printf "Configuring hiera\n"
printf "\n" 

# creating the hiera data directorys
sudo mkdir -p             "$PUPPET_ROOT"/hieradata
sudo mkdir -p             "$PUPPET_ROOT"/hieradata/nodes
sudo mkdir -p             "$PUPPET_ROOT"/hieradata/roles
sudo mkdir -p             "$PUPPET_ROOT"/hieradata/profiles
sudo mkdir -p             "$PUPPET_ROOT"/hieradata/secrets

sudo chown -R root:puppet "$PUPPET_ROOT"/hieradata
sudo chmod -R 770         "$PUPPET_ROOT"/hieradata
sudo chmod -R g+s         "$PUPPET_ROOT"/hieradata

if [ ! -L ""$PUPPET_ROOT"/hiera.yaml" ]
then
   printf "Link to /etc/hiera.yaml does not exist. Linking now\n"
   printf "\n"
   sudo ln -s /etc/hiera.yaml "$PUPPET_ROOT"/hiera.yaml
else
   printf "That is good link to hiera.yaml exists\n"
fi

# manage hiera.yaml 

if ! grep -q ":datadir: "$PUPPET_ROOT"/hieradata" /etc/hiera.yaml 
then
   printf "There is no data path for Hiera... Re-writing hiera.yaml\n"
   printf "\n"

  YAML_CFG="/etc/hiera.yaml"
  HIERA_DIR=":datadir: "$PUPPET_ROOT"/hieradata"

  printf "$HIERA_DIR\n"

sudo echo -e '---'                        | sudo tee     "$YAML_CFG" > /dev/null
sudo echo -e ':backend:'                  | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e '  - yaml'                   | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e ':hierarchy:'                | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e '  - "nodes/%{::fqdn}"'      | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e '  - "roles/%{::role}"'      | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e '  - "profiles/%{::profile}"'| sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e '  - "secrets/%{::secret}"'  | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e '  - "common"'               | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e ':yaml:'                     | sudo tee  -a "$YAML_CFG" > /dev/null
sudo echo -e " "$HIERA_DIR""              | sudo tee  -a "$YAML_CFG" > /dev/null

fi

rsync -zvhr ./hieradata "$PUPPET_ROOT"

printf "\n"
read -p "### Press [Enter] key to continue ###"
clear

################### EOF ################################################
