#!/bin/bash
#
######################
#
# load-modules  
#
# Script to load bootstrap puppet modules     
#
# Loads manifest for this system
# Loads all public modules
# Loads modules to start up
#
# This script installs and configures puppet on centos 7
#
# don't run as root or sudo
#
######################
#
# variables are stored in bootstrap.cfg
# review those settings before running this script

source ./bootstrap.cfg

######################
# Manage manifest for this deployment server

clear

printf "\n"
printf "Manage and Install the Manifest for this deployment server\n"
printf "\n"

HOSTpp=""$MANIFEST_DIR"/`hostname`.pp"

cp ./YourFQDNhostname.pp "$HOSTpp"

sed -i "s/YourFQDNhostname/$MY_FQDN/g" $HOSTpp

printf "\n"
read -p "### Press [Enter] key to continue ###"
clear


######################
# Sync my modules into puppet

###
printf "Install Modules\n"
printf "\n"
rsync -zvhr ./puppet/modules/profile     "$MODULE_DIR" 
rsync -zvhr ./puppet/modules/role        "$MODULE_DIR" 
rsync -zvhr ./puppet/modules/module_tool "$MODULE_DIR" 
rsync -zvhr ./puppet/modules/wget        "$MODULE_DIR" 
rsync -zvhr ./puppet/modules/createrepo  "$MODULE_DIR" 
rsync -zvhr ./puppet/modules/cobbler     "$MODULE_DIR" 
###

printf "\n"
read -p "### Press [Enter] key to continue ###"
clear

######################
# Removing Chronyd        

printf "\n"
printf "Removing Chronyd\n"
printf "\n"
###

sudo systemctl stop chronyd
sudo yum remove chrony

printf "\n"
read -p "### Press [Enter] key to continue ###"
clear
######################
# Run Puppet

sudo /usr/local/bin/papply

printf "\n"
read -p "### Press [Enter] key to continue ###"
clear

########################### EOF #######################################
