#!/bin/bash
#############
#
# Get any variables
#
# Inspect bootstrap.cfg before you execute this script
#
source ./bootstrap.cfg
#
############## seed.manifests
#


printf "\n" 
printf "install public modeles\n"
printf "\n" 

#uninstall chrony and replace it with ntp
sudo systemctl stop chronyd
sudo yum remove chrony
sudo puppet module install --target-dir "$MODULE_DIR" puppetlabs-ntp


printf "\n"
read -p "### Press [Enter] key to continue ###"
clear

############################ EOF ###############################
